name: "Count the number of different lines in a PR"
author: "NMZ0429"
description: "Count the number of different lines in a PR"
branding:
  icon: "git-pull-request"
  color: "blue"
inputs:
  github-token:
    description: "GITHUB_TOKEN"
    required: true
  good-num-lines:
    description: "The number of lines to warn"
    required: false
    default: "300"
  max-num-lines:
    description: "The maximum number of lines to count"
    required: false
    default: "500"
  ignore:
    description: "Files to ignore (gitignore format)"
    required: false
    default: "[]"
  disable-branch:
    description: "If the PR is towards the specified branch, disable the action"
    required: false
    default: ""
outputs:
  num-diff-lines:
    description: "The number of different lines in a PR"
runs:
  using: "node20"
  main: "dist/index.js"
