name: "Count the number of different lines in a PR"
author: "NMZ0429"
description: "Count the number of different lines in a PR"
branding:
  icon: "git-pull-request"
  color: "blue"
inputs:
  github-token:
    description: "GITHUB_TOKEN"
    required: true
outputs:
  num-diff-lines:
    description: "The number of different lines in a PR"

runs:
  using: "node20"
  main: "dist/index.js"
